server:
  port: 8088

spring:
  application:
    name: REVIEW-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/reviewdb
    username: root
    password: root123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
          
      
